apiVersion: v1
kind: Pod
metadata: 
 name: webapp
 labels: 
  app: website
  author: atinsingh
  version: v3
spec:
  containers:
    - image: pragra/webapp2
      name: webapp
      ports:
      - name: http
        containerPort: 80
        protocol: TCP
      resources:
          limits:
            memory: "100Mi"
            cpu: "100m" 