apiVersion: v1
kind: Pod
metadata:
  name: Postgress
  labels:
    app: db
spec:
  containers:
  - name: postgress
    image: postgress:12
    env:
       - name: POSTGRES_USER
         value: dbuser 
       - name: POSTGRES_PASSWORD
         value: dbuser
       - name: POSTGRES_DB
         value: sampledb
  volumeMounts: 
       -  name: db-data
          mountPath: /var/lib/postgressql/data
    ports:
    - name:  containerport
      containerPort: 5432
      protocol: TCP
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m" 
  Volumes:
    - name:db-data
      emptyDir:{}