---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: votedeployment
    spec:
      replicas: Enter the number of replicas
      template:
        metadata:
          labels:
            editor: vscode
        spec:
          containers:
          - name: name
            image: Enter containers image